name: C/C++ CI

on:
  push:
    branches: [ "test-ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install deps 
      run:  sudo apt-get install libsdl2-2.0-0 libsdl2-dev cmake
    - name: setup 
      run: mkdir build && cd build
    - name: configure
      run: cmake ..
    - name: make
      run: make
